### ISSUE TITLE
Several uncertainties

### ISSUE THREAD

**Issue by claumer** [nanoporetech/duplex-tools#16]
Hi there,

I'm trying to run duplex basecalls on a PromethION cDNA dataset made with kit12/R10.4 chemistry. A few items of confusion:

a.) in the data/ directory of guppy 6.1.7 I don't see any configuration file called q20-fixed-2.0-ft-10M.cfg . Where are users meant to find this? Would the standard config file for 1d basecalling, given knowledge of the sequencing kit/flow cell, work in lieu?

b.) I'm trying to run guppy_basecaller_duplex from the 1d-summary as below:

bsub -q gpu-normal -o guppy.out -e guppy.err -gpu "num=1:j_exclusive=yes" -M 20000 -R "rusage[mem=20000] select[mem>20000]"  "./ont-guppy/bin/guppy_basecaller_duplex --input_path 20220613_1523_2E_PAM63315_75942a9f/ -r --save_path 20220613_1523_2E_PAM63315_75942a9f/ -x "cuda:0" --config dna_r10.4_e8.1_sup.cfg --chunks_per_runner 450 --duplex_pairing_mode from_1d_summary --duplex_pairing_file 20220613_1523_2E_PAM63315_75942a9f/sequencing_summary_PAM63315_54e6d536.txt.gz"

But whenever I do I get the error:

"[guppy/error] main: Error: Incomplete row in line 3: expecting 2 columns but got 1
[guppy/warning] main: An error has occurred. Aborting."

I have no idea how to interpret this - would appreciate any input. Am I somehow formulating this command wrong?

c.) Taking a different tack and using duplex_tools first to generate the filtered pair-ids file, I find that the filter_pairs subcommand is a massive memory hog - jobs dying with 100 GB RAM allocated (& 30 cores). Is this normal, and is there anything that can be done to control it?

d.) Finally, one of the other issues threads mentions differences in duplex calling parameters between gDNA and cDNA - is there an up-to-date set of recommendations ONT can provide for cDNA duplexes?

Thanks very much in advance,

Chris L

**Comment by cjw85** [comment]
> I find that the filter_pairs subcommand is a massive memory hog - jobs dying with 100 GB RAM allocated

 If I remember correctly the program reads into memory the first and last section of all reads which are part of a candidate pair in order to perform the pairwise alignments to other reads. The simple alternative is to load read sections on the fly when examining a pair of reads --- that was originally implemented as was very slow due to the random file access involved. Some rearchitecting would be needed to lower the memory use.

 > is there an up-to-date set of recommendations ONT can provide for cDNA duplexes

I'm going to assume given your memory errors that what is happening here is that almost every neighbouring pair of reads is being detected as being a candidate pair due to having similar lengths. Further can foresee that you may get false positive pairs even after the alignment based filtering if your cDNA molecules have common elements at their periphery regardless of their internal structure. For the duplex pairing to be robust you would likely need to use UMIs in the cDNA prep.

I'm afraid I cannot answer your questions a) and b), you might be better asking those in the Nanopore Community.
