### ISSUE TITLE
False positives in filter_pairs when run on linearized plasmid

### ISSUE THREAD

**Issue by eyesmo** [nanoporetech/duplex-tools#20]
Hi there, I'm attempting to do duplex basecalling on a linearized plasmid sample. When I ran filter_pairs on this dataset, it told me 90% of my reads were duplex pairs, which seems unlikely given I'm using Kit 12.

Based on the filtering steps filter_pairs reported, it looks like this tool identifies duplex pairs based on whether two consecutive reads are of roughly the same length, and whether the second strand followed the first through the same pore less than 20 seconds after the first strand finished.

I suspect this method of filtering has a high false positive rate when the sample is something like a linearized plasmid or PCR amplicon, where almost all of the DNA molecules are of the same length. This might even be an issue for variant libraries of plasmids or amplicons, if the 'same length' requirement isn't stringent (I think it said it only checks if the read length difference is less than 10% of the total read length?)

Is there any other method of filtering you might recommend or add to the tool, that could address this challenge? For example, does the second strand in a duplex typically have a different (smaller?) mean Q score than the first strand? Is there a quick-and-dirty alignment tool you'd recommend running on the simplex fastq reads of potential duplex pairs, to confirm that one strand is the reverse complement of the other?

Thanks!

**Comment by eyesmo** [comment]
Better yet, do the sequencing adapters have any UMIs/stretches of random nucleotides embedded within them?

**Comment by eyesmo** [comment]
I think initially used filter_pairs incorrectly. I specified a directory I intended as the output for duplex basecalling, instead of the directory where all the simplex fastq reads were stored.

Running a second time with the simplex fastq reads directory specified, it now says roughly 30% of my reads are good pairs. Still higher than I'd expect for Kit 12, but lower than 90%.

**Comment by onordesjo** [comment]
Hi @eyesmo, 
It's going to be difficult to decide whether a read is a follow-on in most cases where you're sequencing only a single read. If ther are at least a few different sequences in the sample, then these options can be used to adjust the stringency of the match:

`bases_to_align`:
https://github.com/nanoporetech/duplex-tools/blob/master/duplex_tools/filter_pairs.py#L39
`align_threshold`:
https://github.com/nanoporetech/duplex-tools/blob/master/duplex_tools/filter_pairs.py#L40


You're right that one option would be to use UMIs or something similar to identify actual pairs in these cases.

I would suggest to instead spike in some amount of other sequences in these cases to make it easier to identify correct follow-ons. Lambda is typically pretty good as a spike-in for example.

Technically, filter_pairs is quite quick-and-dirty and checks precisely whether a read is rc of the other. The core alignment method happens here, note that seq2 is already reverse-complemented earlier, which is why this works:

https://github.com/nanoporetech/duplex-tools/blob/master/duplex_tools/filter_pairs.py#L220

**Comment by onordesjo** [comment]
Hi, @eyesmo, just wanted to check if you had any luck trying to increase the bases_to_align? It should help fairly well with making sure you have a complement being rc of the template.
